import type {TreeParams} from './penn'

export const TestAspen: TreeParams = {
  Shape: 7,
  BaseSize: 0.4,
  Scale: 13,
  ScaleV: 3,
  ZScale: 1,
  ZScaleV: 0,
  Levels: 3,
  Ratio: 0.015,
  RatioPower: 1.2,
  Lobes: 5,
  LobeDepth: 0.07,
  Flare: 0.6,

  Scale0: 1,
  ScaleV0: 0,
  BaseSplits0: 0,

  LevelParam: [
    // level 0 (trunk)
    {
      DownAngle: 0,
      DownAngleV: 0,
      Rotate: 0,
      RotateV: 0,
      Branches: 0,
      Length: 1,
      LengthV: 0,
      Taper: 1,
      SegSplits: 0,
      SplitAngle: 0,
      SplitAngleV: 0,
      CurveRes: 3,
      Curve: 0,
      CurveBack: 0,
      CurveV: 20,
    },
    // level 1
    {
      DownAngle: 60,
      DownAngleV: -50,
      Rotate: 140,
      RotateV: 0,
      Branches: 50,
      Length: 0.3,
      LengthV: 0,
      Taper: 1,
      SegSplits: 0,
      SplitAngle: 0,
      SplitAngleV: 0,
      CurveRes: 5,
      Curve: -40,
      CurveBack: 0,
      CurveV: 50,
    },
    // level 2
    {
      DownAngle: 45,
      DownAngleV: 10,
      Rotate: 140,
      RotateV: 0,
      Branches: 30,
      Length: 0.6,
      LengthV: 0,
      Taper: 1,
      SegSplits: 0,
      SplitAngle: 0,
      SplitAngleV: 0,
      CurveRes: 3,
      Curve: -40,
      CurveBack: 0,
      CurveV: 75,
    },
    // level 3
    {
      DownAngle: 45,
      DownAngleV: 10,
      Rotate: 77,
      RotateV: 0,
      Branches: 10,
      Length: 0.2,
      LengthV: 0,
      Taper: 1,
      SegSplits: 0,
      SplitAngle: 0,
      SplitAngleV: 0,
      CurveRes: 1,
      Curve: 0,
      CurveBack: 0,
      CurveV: 0,
    },
  ],

  Leaves: 25,
  LeafShape: 0,
  LeafScale: 0.17,
  LeafScaleX: 1,
  AttractionUp: 0.5,
  PruneRation: 0,
  PruneWidth: 0.5,
  PruneWidthPeak: 0.5,
  PrunePowerLow: 0.5,
  PrunePowerHigh: 0.5,
};


export const QuakingAspen: TreeParams = {
  Shape: 7,
  BaseSize: 0.4,
  Scale: 13,
  ScaleV: 3,
  ZScale: 1,
  ZScaleV: 0,
  Levels: 3,
  Ratio: 0.015,
  RatioPower: 1.2,
  Lobes: 5,
  LobeDepth: 0.07,
  Flare: 0.6,

  Scale0: 1,
  ScaleV0: 0,
  BaseSplits0: 0,

  LevelParam: [
    // level 0 (trunk)
    {
      DownAngle: 0,
      DownAngleV: 0,
      Rotate: 0,
      RotateV: 0,
      Branches: 0,
      Length: 1,
      LengthV: 0,
      Taper: 1,
      SegSplits: 0,
      SplitAngle: 0,
      SplitAngleV: 0,
      CurveRes: 3,
      Curve: 0,
      CurveBack: 0,
      CurveV: 20,
    },
    // level 1
    {
      DownAngle: 60,
      DownAngleV: -50,
      Rotate: 140,
      RotateV: 0,
      Branches: 50,
      Length: 0.3,
      LengthV: 0,
      Taper: 1,
      SegSplits: 0,
      SplitAngle: 0,
      SplitAngleV: 0,
      CurveRes: 5,
      Curve: -40,
      CurveBack: 0,
      CurveV: 50,
    },
    // level 2
    {
      DownAngle: 45,
      DownAngleV: 10,
      Rotate: 140,
      RotateV: 0,
      Branches: 30,
      Length: 0.6,
      LengthV: 0,
      Taper: 1,
      SegSplits: 0,
      SplitAngle: 0,
      SplitAngleV: 0,
      CurveRes: 3,
      Curve: -40,
      CurveBack: 0,
      CurveV: 75,
    },
    // level 3
    {
      DownAngle: 45,
      DownAngleV: 10,
      Rotate: 77,
      RotateV: 0,
      Branches: 10,
      Length: 0,
      LengthV: 0,
      Taper: 1,
      SegSplits: 0,
      SplitAngle: 0,
      SplitAngleV: 0,
      CurveRes: 1,
      Curve: 0,
      CurveBack: 0,
      CurveV: 0,
    },
  ],

  Leaves: 25,
  LeafShape: 0,
  LeafScale: 0.17,
  LeafScaleX: 1,
  AttractionUp: 0.5,
  PruneRation: 0,
  PruneWidth: 0.5,
  PruneWidthPeak: 0.5,
  PrunePowerLow: 0.5,
  PrunePowerHigh: 0.5,
};

export const BlackTupelo: TreeParams = {
  Shape: 4,
  BaseSize: 0.2,
  Scale: 23,
  ScaleV: 5,
  ZScale: 1,
  ZScaleV: 0,
  Levels: 4,
  Ratio: 0.015,
  RatioPower: 1.3,
  Lobes: 3,
  LobeDepth: 0.1,
  Flare: 1,

  Scale0: 1,
  ScaleV0: 0,
  BaseSplits0: 0,

  LevelParam: [
    // level 0 (trunk)
    {
        DownAngle: 0,
        DownAngleV: 0,
        Rotate: 0,
        RotateV: 0,
        Branches: 0,
        Length: 1,
        LengthV: 0,
        Taper: 1.1,
        SegSplits: 0,
        SplitAngle: 0,
        SplitAngleV: 0,
        CurveRes: 10,
        Curve: 0,
        CurveBack: 0,
        CurveV: 40,
    },
    // level 1
    {
        DownAngle: 60,
        DownAngleV: -40,
        Rotate: 140,
        RotateV: 0,
        Branches: 50,
        Length: 0.3,
        LengthV: 0.05,
        Taper: 1,
        SegSplits: 0,
        SplitAngle: 0,
        SplitAngleV: 0,
        CurveRes: 10,
        Curve: 0,
        CurveBack: 0,
        CurveV: 90,
    },
    // level 2
    {
        DownAngle: 30,
        DownAngleV: 10,
        Rotate: 140,
        RotateV: 0,
        Branches: 25,
        Length: 0.6,
        LengthV: 0.1,
        Taper: 1,
        SegSplits: 0,
        SplitAngle: 0,
        SplitAngleV: 0,
        CurveRes: 10,
        Curve: -10,
        CurveBack: 0,
        CurveV: 150,
    },
    // level 3
    {
        DownAngle: 45,
        DownAngleV: 10,
        Rotate: 140,
        RotateV: 0,
        Branches: 12,
        Length: 0.4,
        LengthV: 0,
        Taper: 1,
        SegSplits: 0,
        SplitAngle: 0,
        SplitAngleV: 0,
        CurveRes: 1,
        Curve: 0,
        CurveBack: 0,
        CurveV: 0,
    },
    ],


  Leaves: 6,
  LeafShape: 0,
  LeafScale: 0.3,
  LeafScaleX: 0.5,
  AttractionUp: 0.5,
  PruneRation: 0,
  PruneWidth: 0.5,
  PruneWidthPeak: 0.5,
  PrunePowerLow: 0.5,
  PrunePowerHigh: 0.5,
};

export const WeepingWillow: TreeParams = {
  Shape: 3,
  BaseSize: 0.05,
  Scale: 15,
  ScaleV: 5,
  ZScale: 1,
  ZScaleV: 0,
  Levels: 4,
  Ratio: 0.03,
  RatioPower: 2,
  Lobes: 9,
  LobeDepth: 0.03,
  Flare: 0.75,

  Scale0: 1,
  ScaleV0: 0,
  BaseSplits0: 2,

    LevelParam: [
  // level 0 (trunk)
  {
    DownAngle: 0,
    DownAngleV: 0,
    Rotate: 0,
    RotateV: 0,
    Branches: 0,
    Length: 0.8,
    LengthV: 0,
    Taper: 1,
    SegSplits: 0.1,
    SplitAngle: 3,
    SplitAngleV: 0,
    CurveRes: 8,
    Curve: 0,
    CurveBack: 20,
    CurveV: 120,
  },
  // level 1
  {
    DownAngle: 20,
    DownAngleV: 10,
    Rotate: -120,
    RotateV: 30,
    Branches: 25,
    Length: 0.5,
    LengthV: 0.1,
    Taper: 1,
    SegSplits: 0.2,
    SplitAngle: 30,
    SplitAngleV: 10,
    CurveRes: 16,
    Curve: 40,
    CurveBack: 80,
    CurveV: 90,
  },
  // level 2
  {
    DownAngle: 30,
    DownAngleV: 10,
    Rotate: -120,
    RotateV: 30,
    Branches: 10,
    Length: 1.5,
    LengthV: 0,
    Taper: 1,
    SegSplits: 0.2,
    SplitAngle: 45,
    SplitAngleV: 20,
    CurveRes: 12,
    Curve: 0,
    CurveBack: 0,
    CurveV: 0,
  },
  // level 3
  {
    DownAngle: 20,
    DownAngleV: 10,
    Rotate: 140,
    RotateV: 0,
    Branches: 300,
    Length: 0.1,
    LengthV: 0,
    Taper: 1,
    SegSplits: 0,
    SplitAngle: 0,
    SplitAngleV: 0,
    CurveRes: 1,
    Curve: 0,
    CurveBack: 0,
    CurveV: 0,
  },
    ],


  Leaves: 15,
  LeafShape: 0,
  LeafScale: 0.12,
  LeafScaleX: 0.2,
  AttractionUp: -3,
  PruneRation: 1,
  PruneWidth: 0.4,
  PruneWidthPeak: 0.6,
  PrunePowerLow: 0.001,
  PrunePowerHigh: 0.5,
};

export const CABlackOak: TreeParams = {
  Shape: 2,
  BaseSize: 0.05,
  Scale: 10,
  ScaleV: 10,
  ZScale: 1,
  ZScaleV: 0,
  Levels: 3,
  Ratio: 0.018,
  RatioPower: 1.3,
  Lobes: 5,
  LobeDepth: 0.1,
  Flare: 1.2,

  Scale0: 1,
  ScaleV0: 0,
  BaseSplits0: 2,

  LevelParam: [
  // level 0 (trunk)
  {
    DownAngle: 0,
    DownAngleV: 0,
    Rotate: 0,
    RotateV: 0,
    Branches: 0,
    Length: 1,
    LengthV: 0,
    Taper: 0.95,
    SegSplits: 0.4,
    SplitAngle: 10,
    SplitAngleV: 0,
    CurveRes: 8,
    Curve: 0,
    CurveBack: 0,
    CurveV: 90,
  },
  // level 1
  {
    DownAngle: 30,
    DownAngleV: -30,
    Rotate: 80,
    RotateV: 0,
    Branches: 40,
    Length: 0.8,
    LengthV: 0.1,
    Taper: 1,
    SegSplits: 0.2,
    SplitAngle: 10,
    SplitAngleV: 10,
    CurveRes: 10,
    Curve: 40,
    CurveBack: -70,
    CurveV: 150,
  },
  // level 2
  {
    DownAngle: 45,
    DownAngleV: 10,
    Rotate: 140,
    RotateV: 0,
    Branches: 120,
    Length: 0.2,
    LengthV: 0.05,
    Taper: 1,
    SegSplits: 0.1,
    SplitAngle: 10,
    SplitAngleV: 10,
    CurveRes: 3,
    Curve: 0,
    CurveBack: 0,
    CurveV: -30,
  },
    ],

  Leaves: 25,
  LeafShape: 0,
  LeafScale: 0.12,
  LeafScaleX: 0.66,
  AttractionUp: 0.8,
  PruneRation: 0,
  PruneWidth: 0.5,
  PruneWidthPeak: 0.5,
  PrunePowerLow: 0.5,
  PrunePowerHigh: 0.5,
};
